# <font color = dodgerred>**HW1 - 15 Points** </font>
- **You have to submit two files for this part of the HW**
  >(1) ipynb (colab notebook) and<br>
  >(2) pdf file (pdf version of the colab file).**
- **Files should be named as follows**:
>FirstName_LastName_HW_1**


In [ ]:
import torch
import time

# <font color = dodgerred>**Q1 : Create Tensor (1/2 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [ ]:
my_tensor = torch.zeros(5, 3)

In [ ]:
my_tensor.shape

torch.Size([5, 3])

In [ ]:
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Manually set the value at the first row and third column to 10,
# and the value at the third row and first column to 100 in the tensor named "my_tensor".

my_tensor[0, 2] = 10
my_tensor[2, 0] = 100

In [ ]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = dodgerred>**Q2: Reshape tensor (1/2 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [ ]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
x = x.view(6, 4).transpose(0,1)
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = dodgerred>**Q3: Slice tensor (1Point)**

- Slice the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [ ]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [ ]:
x.shape

torch.Size([3, 5])

In [ ]:
# Student Task: Retrieve the last row of the tensor 'x'
# Hint: Negative indexing can help you select rows or columns counting from the end of the tensor.
# Think about how you can select all columns for the desired row.
last_row = x[-1, :]
last_row

tensor([11, 12, 13, 14, 15])

In [ ]:
# Student Task: Retrieve the fourth column of the tensor 'x'
# Hint: Pay attention to the indexing for both rows and columns.
# Remember that indexing in Python starts from zero.
fourth_column = x[:, 3]
fourth_column

tensor([ 4,  8, 14])

In [ ]:
# Student Task: Retrieve the first 3 rows and first 2 columns from the tensor 'x'.
# Hint: Use slicing to extract the required subset of rows and columns.
first_3_rows_2_columns = x[:3, :2]
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [ ]:
# Student Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the required subset of rows and columns with odd indices.
odd_valued_rows_columns = x[::2, ::2]
odd_valued_rows_columns

tensor([[ 1,  3,  5],
        [11, 13, 15]])

#  <font color = dodgerred>**Q4 -Normalize Function (1/2 Points)**<font>

Write the function that normalizes the columns of a matrix. You have to compute the mean and standard deviation of each column. Then for each element of the column, you subtract the mean and divide by the standard deviation.

In [ ]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [ ]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [ ]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [ ]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

In [ ]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [ ]:
def normalize_matrix(x):
  # Calculate the mean along each column (think carefully , you will take mean along axis = 0 or 1)
  mean = torch.mean(x, dim=0)

  # Calculate the standard deviation along each column
  std = torch.std(x, dim=0)

  # Normalize each element in the columns by subtracting the mean and dividing by the standard deviation
  y = (x - mean) / std

  return y  # Return the normalized matrix



In [ ]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [ ]:
Z.mean(axis = 0)

tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08])

# <font color = 'dodgerred'>**Q5: In-place vs. Out-of-place Operations (1 Point)**

1. Create a tensor `A` with values `[1, 2, 3]`.
2. Perform an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, create another tensor `B` with values `[4, 5, 6]` and perform an out-of-place addition of `5`.

**Print the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provide explanation**


In [ ]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:', id(A))
A.add_(5)
print('Memory address of A after in-place addition:', id(A))
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:', id(B))
B = B + 5
print('Memory address of B after out-of-place addition:', id(B))
print('B after out-of-place addition:', B)


Original memory address of A: 133329084446288
Memory address of A after in-place addition: 133329084446288
A after in-place addition: tensor([6, 7, 8])
Original memory address of B: 133329082926240
Memory address of B after out-of-place addition: 133329082927440
B after out-of-place addition: tensor([ 9, 10, 11])


**Provide Explanation for above question here :**

A is a in place operation. This ensures memory address of the tensor remains the same and helps with memory allocation.

B is being created again and assigned the same variable name. Therefore, each time B is created it is alloted a new address.


# <font color = 'dodgerred'>**Q6: Tensor Broadcasting (1 Point)**

1. Create two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Perform an addition operation on `X` and `Y`.
2. Explain how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [ ]:
X = torch.rand((3, 1))
Y = torch.rand((1, 3))
print('Original shapes:', X.shape, Y.shape)
print(X)
print(Y)
result = X + Y
print('Result:', result)
print('Result shape:', result.shape)


Original shapes: torch.Size([3, 1]) torch.Size([1, 3])
tensor([[0.1459],
        [0.1199],
        [0.8207]])
tensor([[0.9270, 0.3545, 0.2465]])
Result: tensor([[1.0729, 0.5004, 0.3924],
        [1.0469, 0.4744, 0.3664],
        [1.7476, 1.1751, 1.0671]])
Result shape: torch.Size([3, 3])


**Provide Explanation for above question here :**

Broadcasting enables the tensors X and Y to be of same shape and it used to perform the Tensor addition

* PyTorch identifies compatible dimensions (here, the first dimension of X and the second dimension of Y have a size of 1).
* It virtually expands those dimensions to match each other, creating intermediate views of X and Y as if they both had a shape of (3, 3).
* This allows element-wise addition to proceed without explicit reshaping.



# <font color = 'dodgerred'>**Q7: Linear Algebra Operations (1 Point)**

1. Create two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, create two vectors `V1` and `V2` and compute their dot product.


In [ ]:
M1 = torch.ones(3,2)
M2 = torch.ones(2,3)
mat_multiplication =  torch.mm(M1,M2)
print('Matrix multiplication result:', mat_multiplication)

V1 = torch.ones(3,)
V2 =  torch.ones(3,)
dot_product =  torch.dot(V1, V2)
print('Dot product:', dot_product)

Matrix multiplication result: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
Dot product: tensor(3.)


# <font color = 'dodgerred'>**Q8: Manipulating Tensor Shapes (1 Point)**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrate how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explain what is the difference between reshape and view

In [ ]:
T = torch.rand(2, 3, 4)
T_view =  T.view(3,8)
print('T_view shape:', T_view.shape)

T_reshape =  T.reshape(4, 2, 3)
print('T_reshape shape:', T_reshape.shape)

T_permute =  T.permute(2, 1, 0)
print('T_permute shape:', T_permute.shape)

T_view shape: torch.Size([3, 8])
T_reshape shape: torch.Size([4, 2, 3])
T_permute shape: torch.Size([4, 3, 2])


**Provide Explanation for above question here :**

View can be only used for contiguous tensor in contrary to reshape.


If you just want to reshape tensors, use torch.reshape. If you're also concerned about memory usage and want to ensure that the two tensors share the same data, use torch.view.



# <font color = 'dodgerred'>**Q9: Tensor Concatenation and Stacking (1 Point)**

Create tensors `C1` and `C2` both with shape (2, 3).
1. Concatenate them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stack the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. What is the difference between stacking and concatinating.

In [ ]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 =  torch.cat([C1, C2], dim=0)
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 =  torch.cat([C1, C2], dim=1)
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked =  torch.stack([C1, C2], dim=0)
print('Stacked tensor shape:', stacked.shape)


Concatenated along dimension 0: torch.Size([4, 3])
Concatenated along dimension 1: torch.Size([2, 6])
Stacked tensor shape: torch.Size([2, 2, 3])


**Explain the diffrence between concatinating and stacking here**

Concatinating combines tensors along an existing dimnesion, whereas stacking adds a dimension and adds the tensors along that dimension.



# <font color = 'dodgerred'>**Q10: Advanced Indexing and Slicing (1 Point)**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extract the second and fourth rows from `D`.
3. Finally, extract a sub-tensor from the top-left 3x3 block.

In [ ]:
D = torch.rand(6, 6)
print('Elements greater than 0.5:\n',  D[D > 0.5])

second_fourth_rows =  D[[1, 3], :]
print('\nSecond and fourth rows:\n', second_fourth_rows)

top_left_3x3 =  D[:3, :3]
print('\nTop-left 3x3 block:\n ', top_left_3x3)

Elements greater than 0.5:
 tensor([0.6884, 0.8273, 0.6424, 0.8448, 0.8425, 0.5156, 0.6234, 0.9275, 0.6874,
        0.6476, 0.8045, 0.6582, 0.8050, 0.9965, 0.6037, 0.6547, 0.9343])

Second and fourth rows:
 tensor([[0.2232, 0.0988, 0.6424, 0.8448, 0.8425, 0.2920],
        [0.9275, 0.1603, 0.4000, 0.6874, 0.6476, 0.2764]])

Top-left 3x3 block:
  tensor([[0.3689, 0.3303, 0.6884],
        [0.2232, 0.0988, 0.6424],
        [0.0851, 0.5156, 0.6234]])


# <font color = 'dodgerred'>**Q11: Tensor Mathematical Operations (1 Point)**

1. Create a tensor `G` with values from 0 to π in steps of π/4.
2. Compute and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [ ]:
import numpy as np
G = torch.arange(0, torch.tensor(np.pi), step=torch.tensor(np.pi / 4))

print('G:', G)
print('Sine of G:',  torch.sin(G))
print('Cosine of G:',  torch.cos(G))
print('Tangent of G:',  torch.tan(G))
print('Natural logarithm of G:',  torch.log(G))
print('Exponential of G:',  torch.exp(G))


G: tensor([0.0000, 0.7854, 1.5708, 2.3562])
Sine of G: tensor([0.0000, 0.7071, 1.0000, 0.7071])
Cosine of G: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01])
Tangent of G: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00])
Natural logarithm of G: tensor([   -inf, -0.2416,  0.4516,  0.8570])
Exponential of G: tensor([ 1.0000,  2.1933,  4.8105, 10.5507])


# <font color = 'dodgerred'>Q12: **Tensor Reduction Operations (1 Point)**

1. Create a 3x2 tensor `H`.
2. Compute the sum of `H`. Print the result and shape after taking sun.
3. Then, perform the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do you observe? How the shape changes?

In [ ]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

print('Sum of H:',  torch.sum(H))
print('Shape after Sum of H:', torch.sum(H).shape,  end = "\n\n")

print('Sum of H along dimension 0:',  torch.sum(H, dim = 0))
print('Shape after sum of H along dimension 0:',  torch.sum(H, dim = 0).shape,  end = "\n\n")

print('Sum of H along dimension 1:', torch.sum(H, dim = 1))
print('Shape after sum of H along dimension 1:',  torch.sum(H, dim = 1).shape)


H: tensor([[0.8592, 0.7686],
        [0.8398, 0.4198],
        [0.2565, 0.4445]])

Shape of original Tensor H torch.Size([3, 2])

Sum of H: tensor(3.5884)
Shape after Sum of H: torch.Size([])

Sum of H along dimension 0: tensor([1.9556, 1.6329])
Shape after sum of H along dimension 0: torch.Size([2])

Sum of H along dimension 1: tensor([1.6278, 1.2596, 0.7011])
Shape after sum of H along dimension 1: torch.Size([3])


**Provide your observations on shape changes here**

1. Is the sum of all the scalars in the Tensor H, therefore it is a scalar.

2. Is the sum along dimension 0 (rows), therefore it is a scalar of dimension (2,).

3. Is the sum along dimension 1 (columns), therefore it is a scalar of dimension (3,).

# <font color = 'dodgerred'>**Q13: Working with Tensor Data Types (1 Point)**

1. Create a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Convert `I` to data type int and print the result.
3. Explain in which scenarios it's necessary to be cautious about the data type of tensors.

In [ ]:
# Solution for Q16
I =  torch.tensor([1.0, 2.0, 3.0], dtype=torch.float)
print('I:', I)
I_int =  I.to(dtype=torch.int)
print('I converted to int:', I_int)

I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**Your explanations here**

Memory usage, precision loss and gradient computation are the reasons to be cautiuos.



# <font color = 'dodgerred'>**Q14. Speedtest for vectorization 1.5 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [ ]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = torch.randn(1024, 1024)
B = torch.randn(1024, 1024)

In [ ]:
## Solution 2
start=time.time()

C = torch.mm(A, B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.042911529541015625 seconds


In [ ]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

C = torch.zeros(1024, 1024)
for i in range(B.size(1)):
    C[:, i] = torch.mv(A, B[:, i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.3060941696166992 seconds


In [ ]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

C = torch.zeros(1024, 1024)
for i in range(A.size(1)):
    for j in range(B.size(1)):
        C[i, j] = torch.dot(A[:, i], B[:, j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 44.67663264274597 seconds


# <font color = 'dodgerred'>**Q15 : Redo Question 14 by using GPU - 1.5 Points**

<font size = 4, color = 'dodgerred'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [ ]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [ ]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [ ]:
print(A)
print(B)

tensor([[ 0.1940,  2.1614, -0.1721,  ...,  2.8564,  0.6748,  2.0562],
        [ 0.8234, -2.3821,  1.2520,  ...,  1.4540, -2.7733, -0.8932],
        [-0.4574,  0.8063,  0.1580,  ..., -0.6279,  0.7594, -2.4643],
        ...,
        [ 0.7528, -0.3422,  0.6958,  ..., -0.0805,  0.7321, -0.4877],
        [-0.4304, -1.8875, -0.0588,  ..., -1.7712, -0.6523, -1.0117],
        [ 0.1621, -0.1626,  0.8502,  ...,  1.0908, -0.7354, -0.8094]],
       device='cuda:0')
tensor([[ 7.8214e-01,  1.3969e+00, -1.8156e-01,  ...,  1.0963e+00,
          2.2060e+00,  4.9150e-01],
        [ 9.7876e-01, -1.0868e+00,  7.6596e-01,  ...,  2.0217e+00,
         -4.4059e-01, -1.2401e+00],
        [ 1.1979e+00,  1.9029e+00, -5.8293e-01,  ...,  5.8142e-01,
          5.5776e-01, -4.1612e-01],
        ...,
        [ 7.5334e-01, -1.7123e-01, -2.2482e+00,  ..., -9.0756e-01,
          6.6091e-01,  8.7813e-01],
        [ 1.4010e+00,  8.1821e-01, -1.3200e-03,  ..., -5.0882e-01,
          1.4235e+00,  8.6407e-01],
        [-1.13

In [ ]:
## Solution 2
start=time.time()

C = torch.mm(A, B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.11477398872375488 seconds


In [ ]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

C = torch.zeros(1024, 1024)
for i in range(B.size(1)):
    C[:, i] = torch.mv(A, B[:, i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.1631183624267578 seconds


In [ ]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

C = torch.zeros(1024, 1024)
for i in range(A.size(1)):
    for j in range(B.size(1)):
        C[i, j] = torch.dot(A[:, i], B[:, j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 53.51922106742859 seconds
