# <font color = dodgerred>**HW1 - 15 Points** </font>
- **You have to submit two files for this part of the HW**
  >(1) ipynb (colab notebook) and<br>
  >(2) pdf file (pdf version of the colab file).**
- **Files should be named as follows**:
>FirstName_LastName_HW_1**


In [2]:
import torch
import time

# <font color = dodgerred>**Q1 : Create Tensor (1/2 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [ ]:
my_tensor = # CODE HERE

In [ ]:
my_tensor.shape

torch.Size([5, 3])

In [ ]:
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Manually set the value at the first row and third column to 10,
# and the value at the third row and first column to 100 in the tensor named "my_tensor".

# CODE HERE

In [ ]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = dodgerred>**Q2: Reshape tensor (1/2 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [ ]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [ ]:
x = # CODE HERE
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = dodgerred>**Q3: Slice tensor (1Point)**

- Slice the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [ ]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [ ]:
x.shape

torch.Size([3, 5])

In [ ]:
# Student Task: Retrieve the last row of the tensor 'x'
# Hint: Negative indexing can help you select rows or columns counting from the end of the tensor.
# Think about how you can select all columns for the desired row.
last_row = # CODE HERE
last_row

tensor([11, 12, 13, 14, 15])

In [ ]:
# Student Task: Retrieve the fourth column of the tensor 'x'
# Hint: Pay attention to the indexing for both rows and columns.
# Remember that indexing in Python starts from zero.
fourth_column = # CODE HERE
fourth_column

tensor([ 4,  8, 14])

In [ ]:
# Student Task: Retrieve the first 3 rows and first 2 columns from the tensor 'x'.
# Hint: Use slicing to extract the required subset of rows and columns.
first_3_rows_2_columns = # CODE HERE
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [ ]:
# Student Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the required subset of rows and columns with odd indices.
odd_valued_rows_columns = # CODE HERE
odd_valued_rows_columns

tensor([[ 1,  3,  5],
        [11, 13, 15]])

#  <font color = dodgerred>**Q4 -Normalize Function (1/2 Points)**<font>

Write the function that normalizes the columns of a matrix. You have to compute the mean and standard deviation of each column. Then for each element of the column, you subtract the mean and divide by the standard deviation.

In [ ]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [ ]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [ ]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [ ]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

In [ ]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [ ]:
def normalize_matrix(x):
  # Calculate the mean along each column (think carefully , you will take mean along axis = 0 or 1)
  mean = # CODE HERE

  # Calculate the standard deviation along each column
  std = # CODE HERE

  # Normalize each element in the columns by subtracting the mean and dividing by the standard deviation
  y = # CODE HERE

  return y  # Return the normalized matrix



In [ ]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [ ]:
Z.mean(axis = 0)

tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08])

# <font color = 'dodgerred'>**Q5: In-place vs. Out-of-place Operations (1 Point)**

1. Create a tensor `A` with values `[1, 2, 3]`.
2. Perform an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, create another tensor `B` with values `[4, 5, 6]` and perform an out-of-place addition of `5`.

**Print the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provide explanation**


In [ ]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:', # CODE HERE)
# CODE HERE
print('Memory address of A after in-place addition:', # CODE HERE)
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:', # CODE HERE)
# CODE HERE
print('Memory address of B after out-of-place addition:', # CODE HERE)
print('B after out-of-place addition:', B)


**Provide Explanation for above question here :**



# <font color = 'dodgerred'>**Q6: Tensor Broadcasting (1 Point)**

1. Create two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Perform an addition operation on `X` and `Y`.
2. Explain how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [ ]:
X = # CODE HERE
Y = # CODE HERE
print('Original shapes:', X.shape, Y.shape)
result = # CODE HERE
print('Result:', result)
print('Result shape:', result.shape)


**Provide Explanation for above question here :**



# <font color = 'dodgerred'>**Q7: Linear Algebra Operations (1 Point)**

1. Create two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, create two vectors `V1` and `V2` and compute their dot product.


In [ ]:
M1 = # CODE HERE
M2 = # CODE HERE
mat_multiplication =  # CODE HERE
print('Matrix multiplication result:', mat_multiplication)

V1 = # CODE HERE
V2 =  # CODE HERE
dot_product =  # CODE HERE
print('Dot product:', dot_product)


Matrix multiplication result: tensor([[19, 22],
        [43, 50]])
Dot product: tensor(32)


# <font color = 'dodgerred'>**Q8: Manipulating Tensor Shapes (1 Point)**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrate how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explain what is the difference between reshape and view

In [ ]:
T = torch.rand(2, 3, 4)
T_view =  # CODE HERE
print('T_view shape:', T_view.shape)

T_reshape =  # CODE HERE
print('T_reshape shape:', T_reshape.shape)

T_permute =  # CODE HERE
print('T_permute shape:', T_permute.shape)

**Provide Explanation for above question here :**



# <font color = 'dodgerred'>**Q9: Tensor Concatenation and Stacking (1 Point)**

Create tensors `C1` and `C2` both with shape (2, 3).
1. Concatenate them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stack the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. What is the difference between stacking and concatinating.

In [ ]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 =  # CODE HERE
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 =  # CODE HERE
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked =  # CODE HERE
print('Stacked tensor shape:', stacked.shape)


**Explain the diffrence between concatinating and stacking here**




# <font color = 'dodgerred'>**Q10: Advanced Indexing and Slicing (1 Point)**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extract the second and fourth rows from `D`.
3. Finally, extract a sub-tensor from the top-left 3x3 block.

In [ ]:
D = torch.rand(6, 6)
print('Elements greater than 0.5:\n',  # CODE HERE)

second_fourth_rows =  # CODE HERE
print('\nSecond and fourth rows:\n', second_fourth_rows)

top_left_3x3 =  # CODE HERE
print('\nTop-left 3x3 block:\n ', top_left_3x3)


# <font color = 'dodgerred'>**Q11: Tensor Mathematical Operations (1 Point)**

1. Create a tensor `G` with values from 0 to π in steps of π/4.
2. Compute and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [ ]:
G = t # CODE HERE
print('G:', G)
print('Sine of G:',  # CODE HERE)
print('Cosine of G:',  # CODE HERE)
print('Tangent of G:',  # CODE HERE)
print('Natural logarithm of G:',  # CODE HERE)
print('Exponential of G:',  # CODE HERE)


# <font color = 'dodgerred'>Q12: **Tensor Reduction Operations (1 Point)**

1. Create a 3x2 tensor `H`.
2. Compute the sum of `H`. Print the result and shape after taking sun.
3. Then, perform the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do you observe? How the shape changes?

In [ ]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

print('Sum of H:',  # CODE HERE)
print('Shape after Sum of H:',  # CODE HERE,  end = "\n\n")

print('Sum of H along dimension 0:',  # CODE HERE)
print('Shape after sum of H along dimension 0:',  # CODE HERE,  end = "\n\n")

print('Sum of H along dimension 1:', # CODE HERE)
print('Shape after sum of H along dimension 1:',  # CODE HERE)


**Provide your observations on shape changes here**



# <font color = 'dodgerred'>**Q13: Working with Tensor Data Types (1 Point)**

1. Create a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Convert `I` to data type int and print the result.
3. Explain in which scenarios it's necessary to be cautious about the data type of tensors.

In [ ]:
# Solution for Q16
I =  # CODE HERE
print('I:', I)
I_int =  # CODE HERE
print('I converted to int:', I_int)

I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**Your explanations here**



# <font color = 'dodgerred'>**Q14. Speedtest for vectorization 1.5 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [ ]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = # code here
B = # code here

In [ ]:
## Solution 2
start=time.time()

C = # code here

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

In [ ]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

# code here

print("Matrix by vector: " + str(time.time()-start) + " seconds")

In [ ]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

# code here

print("vector by vector: " + str(time.time()-start) + " seconds")

# <font color = 'dodgerred'>**Q15 : Redo Question 14 by using GPU - 1.5 Points**

<font size = 4, color = 'dodgerred'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [ ]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

In [ ]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [ ]:
## Solution 2
start=time.time()

C = # code here

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

In [ ]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

# code here

print("Matrix by vector: " + str(time.time()-start) + " seconds")

In [ ]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

# code here

print("vector by vector: " + str(time.time()-start) + " seconds")